version: '3.3'
services:
  maven:
    image: maven:3.6.2-jdk-8
    command: sleep inf
    volumes:
      - m2:/root/.m2/repository
      - .:/tn
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins:
    image: public.ecr.aws/c7o8u9c1/reem_jdk8:latest
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080" 
    networks:
      - jen_arti         
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    hostname: 'gitlab.example.com'
    ports:
      - '80:80'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.16.0
    ports:
      - "8081:8081"
    volumes:
      - art_data:/var/opt/jfrog/artifactory
    networks:
      - jen_arti
 

networks:
  jen_arti:
volumes:
  jenkins_home:
  m2:
  art_data:
    
  